# Generated by Django 4.2.7 on 2023-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
